#!/usr/bin/env bash
# Script to open the changelogs of some apps I'm interested in, in the default
# web browser.  Mostly written by my friend Gemini.

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# Dictionary of application names and their changelog URLs
declare -A changelog_urls=(
    ["kitty"]="https://sw.kovidgoyal.net/kitty/changelog"
    ["mise"]="https://github.com/jdx/mise/releases"
    ["python"]="https://docs.python.org/3/whatsnew/changelog.html"
    ["ruff"]="https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md"
    ["uv"]="https://github.com/astral-sh/uv/blob/main/CHANGELOG.md"
)

# Check if an application name was provided as an argument
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <application_name>"
    echo "Available applications:"
    for app in "${!changelog_urls[@]}"; do
        echo "  - $app"
    done
    exit 1
fi

app_name="$1"

# Check if the provided application name is valid
if [[ ${changelog_urls[$app_name]} ]]; then
    url="${changelog_urls[$app_name]}"
    echo "Opening changelog for $app_name: $url"
    xdg-open "$url" &> /dev/null
else
    echo "Invalid application name: $app_name"
    echo "Available applications:"
    for app in "${!changelog_urls[@]}"; do
        echo "  - $app"
    done
fi
