#!/bin/bash
# Small script to show Docker/docker-compose versions on docker application hosts.

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

for n in $(dockerhosts)
do
  echo "========= $n =========="
  ssh $n "docker --version ; echo ; docker-compose version" || true
  echo ""
done
