#!/bin/bash
# Small script to show Docker/docker-compose versions on docker01-05.
for n in 01 02 03 04 05 06 07
do
  echo "========= docker$n =========="
  ssh docker$n.eng.arbor.net "docker --version ; echo ; docker-compose version"
  echo ""
done
