#! /usr/bin/env bash
# Small script to show load and free memory on docker01-05.

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

for n in $(dockerhosts)
do
  echo "========= $n =========="
  ssh $n "docker --version ; uptime ; free -hm ; df -h /data" || true
  echo ""
done
