#!/bin/bash
# Small script to show apps running on docker application hosts.

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

for n in $(dockerhosts)
do
  echo "========= $n =========="
  ssh $n "ls -F | grep /" || true
  echo ""
done
