#!/bin/sh

# Note, this was written for Ubuntu 17.04 and higher, which uses systemd, so it should work for any other systemd Linux.
# The flush-caches trick doesn't seem to work now.  Restarting systemd-resolved appears to though.
# https://linuxhint.com/flush_dns_cache_ubuntu/

sudo systemd-resolve --statistics
sudo systemd-resolve --flush-caches
sudo systemctl restart systemd-resolved
sudo systemd-resolve --statistics