#!/bin/bash

set -o errexit
#set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ -z "$1" ]]; then
    dryrun=
else
    case "$1" in
    check|dry-run|--check|-n)
        dryrun=-ni
    ;;
help|--help|-h)
        echo ""
        echo "Usage: john-sync [--check]"
        echo ""
        echo "Synchronise local changes to john.eng.netscout.com"
        echo ""
        echo "Optionas:"
        echo "  check  Dry run mode."
        echo ""
        exit
    esac
fi

echo BIN
rsync $dryrun --delete -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/bin/* john.eng.netscout.com:bin/

# echo ZSH Configs
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/.zsh{env,rc} $HOME/.p10k.zsh john.eng.netscout.com:

echo Select Configs from ~/.config
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/.config/{bin,broot,mise,pip,ruff,thefuck,tlrc,uv,yazi,ripgrep} john.eng.netscout.com:.config/

echo Docker Config for logins
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/.docker/config.json john.eng.netscout.com:.docker/

echo GIT Configs
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/.git{config,ignore} john.eng.netscout.com:

echo SSH Shit
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/.ssh/* john.eng.netscout.com:.ssh/

echo All MISE       
rsync $dryrun -azvHP -e "ssh -i $HOME/.ssh/id_rsa" \
        --rsync-path="sudo rsync" \
        $HOME/allmise/* john.eng.netscout.com:allmise/
