#!/usr/bin/env bash
# 

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ $# -lt 2 ]]; then
    echo Usage: $(basename $0) [PYTHON-VERSION] [PACKAGE...]
    echo ""
    echo "Uninstalls and installs the pipx PACKAGE(s) using the specified Python"
    echo "which is assumed to be an existing Python installed with rtx."
    exit 0
fi

pyver=$1
shift

if [[ -z $(rtx where python@$pyver) ]]; then
    echo "rtx where python@$pyver failed, check to make sure $1 is installed in rtx."
    exit 1
fi

while (( "$# ")); do
    [[ -n "$(pipx runpip $1 list)" ]] && pipx uninstall "$1"
    pipx install --python $(rtx where python@$pyver)/bin/python "$1"
    shift
done