#!/usr/bin/env bash

# Small script to look up sAMAccountName for one or more email addresses.
# Provide full email addresses like: john.gaines@netscout.com

for e in "$@"; do
    echo "$e -> $(ldapsearch -x -H ldap://arbdc-01.netscout.com -D svc-arbor-eng-ldap@netscout.com \
               -w 'C?)5BYzfPW(?pM{T' -b 'DC=netscout,DC=com' \
               -s sub \(proxyAddresses="SMTP:$e"\) | grep sAMAccountName | cut -d' ' -f2)"
done
