#!/usr/bin/env bash

# Small script to look up sAMAccountName for one or more email addresses.
# Provide full email addresses like: john.gaines@netscout.com

for e in "$@"; do
    echo "$e -> $(ldapsearch -x -H ldap://netscout.com -D svc-arbor-eng-ldap@netscout.com \
               -y ~/.ssh/ldap_bind_password -b 'DC=netscout,DC=com' \
               -s sub \(proxyAddresses="SMTP:$e"\) | grep sAMAccountName | cut -d' ' -f2)"
done
