#!/usr/bin/env bash

set -o errexit
set -o nounset
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# "source cat" cat a file with source highlighting
# requires pygmentize python app to be installed

if [ ! -t 0 ] ; then
	file=/dev/stdin
elif [[ -n "$1" && -e "$1" ]] ; then
	file=$1
	shift
else
	echo "Usage: $0 [options] [FILE]"
	echo "or e.g. head code.c | $0"
	echo
	echo "Options:"
	echo "	-l <lang>	Language"
	exit 1
fi

pygmentize -f terminal256 -O style=monokai -g "$@" "$file"
