#!/bin/bash

LOG=~/.local/log/start.log

mkdir -p "$(dirname $LOG)"

date > "$LOG"
emacs --daemon &>> "$LOG" &
firefox &>> "$LOG" &
slack &>> "$LOG" &
# exo-open --launch WebBrowser &>> "$LOG" &
signal-reset pycharmp &>> "$LOG" &
# xfce4-terminal --tab --tab --tab &>> "$LOG"
edit -c &>> "$LOG" &
