#!/bin/sh
touchpad="DLL06E5:01 06CB:7A13 Touchpad"
case "$1" in
on)
	xinput set-prop "$touchpad" "Device Enabled" 1
;;
off)
	xinput set-prop "$touchpad" "Device Enabled" 0
;;
show|st|stat|status)
	xinput list-props "$touchpad" | grep "Device Enabled"
;;
*)
	echo ""
	echo "Usage: touchpad [COMMAND]"
	echo ""
	echo "Enable/disable touchpad so I can use laptop without wanting to chuck it"
	echo "out the nearest window."
	echo ""
	echo "Commands:"
	echo "  help    shows this help"
	echo "  on      enable touchpad"
	echo "  off     disable touchpad"
	echo "  show    show status"
	echo ""
esac
