#!/bin/sh
# This will upgrade kittyer terminal in place in ~/.local/kitty.app
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

# open https://sw.kovidgoyal.net/kitty/changelog in default browser and detatch process from this terminal.
xdg-open https://sw.kovidgoyal.net/kitty/changelog &
disown
