#!/bin/bash
echo "Current Language Versions"
echo

iscmd() {
    cmd=$(which $1 2> /dev/null)
    if [ -x "$cmd" ]
    then
        return 0
    else
        return 1
    fi
}

if iscmd erl
then
    echo "Erlang    $(erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell)"
    echo "          $(which erl)"
    # echo "          Use evm to change."
    echo
else
    echo "Erlang    (none installed)"
    echo
fi

if iscmd julia
then
    # All this goofiness is because I hate waiting for julia to load
    # just to display the version.  This junk extracts the version
    # info from the build_h.jl file.
    # build_h="/usr/share/julia/base/build_h.jl"
    # if [ -e  $build_h ]
    # then
    #     ver=$(grep BUILD_INFO $build_h|cut -d' ' -f5|tr -d '",')
    #     pre=$(grep BUILD_INFO $build_h|cut -d',' -f8|tr -d ' )')
    #     if [ "$pre" = "true" ]
    #     then
    #         pre="-prerelease"
    #     else
    #         pre=""
    #     fi
    #     bld=$(grep BUILD_INFO $build_h|cut -d',' -f5|tr -d ' ')
    #     echo "Julia     $ver$pre+$bld"
    # else
	echo "Julia     $(julia -v 2>&1)"
    # fi
    echo "          $(which julia)"
    echo
fi

if iscmd node
then
    echo "Node.js   $(node -v 2>&1)"
    echo "          $(which node)"
    echo "          Use nvm to change."
    echo
else
    echo "Node.js   (none active)"
    if [ -s "$HOME/.nvm/nvm.sh" ]
    then
	echo "          Use nvm to change."
	echo
    else
	echo "          Install nvm to manage Node.js"
	echo
    fi
fi

if iscmd ocaml
then
    echo "Ocaml     $(ocaml -version 2>&1)"
    echo "          $(which ocaml)"
    # echo "          Installed with ocamlbrew (~/ocamlbrew/ocamlbrew -h)."
    echo
else
    echo "Ocaml     (none installed)"
    echo
fi

if iscmd perl
then
    echo "Perl      $(perl -e 'print $]')"
    echo "          $(which perl)"
    # echo "          Use perlbrew to change."
    echo
fi

if iscmd pure
then
    echo "Pure      $(pure --version|head -1|cut -d' ' -f2-)"
    echo "          $(which pure)"
    echo
fi

if iscmd python
then
    echo "Python    $(python -V 2>&1)"
    echo "          $(which python)"
    # echo "          Use pyenv to change."
    echo
fi

if iscmd ruby
then
    echo "Ruby      $(ruby -v 2>&1)"
    echo "          $(which ruby)"
    # echo "          $RUBY_MANAGE"
    echo
fi

if iscmd java
then
    echo "Java      $(java -version 2>&1)"
    echo
fi

if [ "$1" == "" ]
then
    exit 0
fi

iscmd bash      && echo "Bash      $(bash --version | head -1)"
iscmd csc       && echo "Chicken   $(csc -version | grep Version)"
iscmd gawk      && echo "gawk      $(gawk --version | head -1)"
iscmd gcc       && echo "gcc       $(gcc --version | head -1)"
iscmd guile     && echo "guile     $(guile -v | head -1)"
iscmd hackersh  && echo "hackersh  $(hackersh -V 2>&1)"
iscmd lua       && echo "lua       $(lua -v)"
iscmd pythonect && echo "pythonect $(pythonect -V 2>&1)"
iscmd racket    && echo "racket    $(racket -v)"
iscmd sbcl      && echo "SBCL      $(sbcl --version | cut -d' ' -f2)"
iscmd slsh      && echo "slsh      $(slsh --version)"
iscmd tclsh     && echo "tcl       $(echo 'puts $tcl_version' | tclsh)"
iscmd zsh       && echo "zsh       $(zsh --version)"
echo

iscmd bzr     && echo "bzr       $(bzr version | head -1)"
iscmd fossil  && echo "fossil    $(fossil -v)"
iscmd git     && echo "git       $(git version)"
iscmd hg      && echo "hg        $(hg version | head -1)"
iscmd svn     && echo "svn       $(svn --version | head -1)"
echo
