#!/bin/bash
sudo openconnect \
    --csd-wrapper="$HOME/git/third-party/openconnect/trojans/csd-post.sh" \
    --authgroup=Tunnel-All-VPN \
    --user="$USER" \
    --pid-file=/var/run/openconnect.pid \
    --background \
    annarbor.netscout.com
