#!/bin/bash
# Simple script to connect VPN (along with helpful comments for me).
echo Answer push to Password#2 prompt.
sudo openconnect --juniper -pfs -b -u "$USER" secure.ma.arbor.net
echo ifconfig should show tun0 interface if all went well.
ifconfig | grep tun0
